PR Semana 7 - Aitorias#9443
undefined-academy/semana-7 pull request #13
Opened 2023-05-30 09:57 UTC by aitorias

- [x] Crear aplicación con Next.js en su versión 13.4.3 utilizando App Router
- [x] Gestionar el contenido de la aplicación mostrando los resultados consumiendo la API: [Dog Api](https://dog.ceo/dog-api/)

2023-05-30 12:57 UTC, marisolSv22 requested changes
Deberías colocar tu lógica (getDogs) en una carpeta llamada api y que esta muestre como tal la raza de los perros

2023-05-31 15:43 UTC, aitorias commented
> Deberías colocar tu lógica (getDogs) en una carpeta llamada api y que esta muestre como tal la raza de los perros

@marisolSv22 muchas gracias por el comentario y ayudarme a revisar mi PR!

Hice los cambios de reestructura del archivo de la lógica de la API y correcciones para mostrar las razas en la aplicación.

Espero que me pudieras ayudar a validar los cambios nuevamente. ¡Muchas gracias! 😄

2023-05-31 16:06 UTC, marisolSv22 approved these changes
Buen trabajo!

2023-06-07 13:58 UTC, lucianogarriga approved these changes
Hola, analizado el proyecto se ve el código bastante prolijo y completo. El diseño de la web está ok e incluiste el responsive también. Felicidades buen trabajo!

2023-06-07 15:01 UTC, aitorias commented
> Buen trabajo!

¡Muchas gracias por la revisión @marisolSv22! 😄

2023-06-07 15:02 UTC, aitorias commented
> Hola, analizado el proyecto se ve el código bastante prolijo y completo. El diseño de la web está ok e incluiste el responsive también. Felicidades buen trabajo!

¡Muchas gracias por validarle la PR @lucianogarriga! 😄

2023-06-07 15:07 UTC, lucianogarriga commented
> > Hola, analizado el proyecto se ve el código bastante prolijo y completo. El diseño de la web está ok e incluiste el responsive también. Felicidades buen trabajo!
> 
> ¡Muchas gracias por validarle la PR @lucianogarriga! 😄

Te agradecería si puedes revisar mi PR @aitorias  😃 Es la #15

2023-06-07 15:08 UTC, aitorias commented
> > > Hola, analizado el proyecto se ve el código bastante prolijo y completo. El diseño de la web está ok e incluiste el responsive también. Felicidades buen trabajo!
> > 
> > 
> > ¡Muchas gracias por validarle la PR @lucianogarriga! 😄
> 
> Te agradecería si puedes revisar mi PR @aitorias 😃 Es la #15

¡Claro, sin problema! Justamente estaba en ello @lucianogarriga 👍

2023-06-07 21:56 UTC, merged