Semana 7, API dogs, Dev Ardila
undefined-academy/semana-7 pull request #14
Opened 2023-06-02 14:28 UTC by jaardila-3

# Proyecto de Next.js y API de perritos

En este proyecto, hemos creado una aplicación web utilizando el marco de trabajo Next.js para consumir el API de perritos y mostrar una lista de 10 razas con su respectiva foto.

## Comandos utilizados

hemos instalado Bootstrap en el proyecto utilizando el siguiente comando: ` npm install bootstrap` y se importa en el _app.js así: `import 'bootstrap/dist/css/bootstrap.css';`

Este comando utiliza `npm` para instalar el paquete `bootstrap` en el proyecto.

## Descripción del código

Para consumir el API de perritos y mostrar la lista de razas, hemos utilizado el hook `useEffect` de React para hacer una solicitud al API y obtener la lista de razas. Luego, hemos utilizado el hook `useState` para guardar las razas en el estado y mostrarlas en la página utilizando un componente de lista.

También hemos utilizado Bootstrap para estilizar la página y mostrar las imágenes en una grilla de dos columnas por cinco filas. Hemos agregado clases de Bootstrap a los elementos HTML y hemos utilizado estilos personalizados para ajustar el tamaño y la posición de las imágenes.

2023-06-02 16:21 UTC, zucerkia requested changes

2023-06-02 16:21 UTC, zucerkia commented on nextjs/jaardila-4569/pages/dogs.js
> +            .then(response => response.json())
La lógica la veo bien. pero te recomiendo para un futuro separar la responsabilidad del componente de la obtención y manipulación de los datos.

2023-06-02 16:21 UTC, zucerkia commented on nextjs/package-lock.json
Este archivo se debe eliminar ya que dentro de tu proyecto ya existe el archivo y este está por fuera de tu carpeta
![image](https://github.com/undefined-academy/semana-7/assets/32274355/22c968c1-aa78-4ea5-84d4-e8ff23d59eb0)

2023-06-02 16:21 UTC, zucerkia commented on nextjs/package.json
Este archivo se debe eliminar ya que dentro de tu proyecto ya existe el archivo y este está por fuera de tu carpeta
![image](https://github.com/undefined-academy/semana-7/assets/32274355/22c968c1-aa78-4ea5-84d4-e8ff23d59eb0)

2023-06-02 17:07 UTC, jaardila-3 commented on nextjs/jaardila-4569/pages/dogs.js
> +            .then(response => response.json())
lo tendré en cuenta. mil gracias

2023-06-02 17:08 UTC, jaardila-3 commented on nextjs/package.json
corregido.

2023-06-02 17:08 UTC, jaardila-3 commented on nextjs/package-lock.json
corregido.

2023-06-02 21:58 UTC, zucerkia approved these changes

2023-06-02 23:23 UTC, estebancelis approved these changes
se verifica y cumple con lo solicitado  en la tarea

2023-06-04 22:03 UTC, merged

2023-06-09 02:16 UTC, jaiver-1 reviewed
Cuemple Con todos los soportes requeridos