Api dog con nextjs
undefined-academy/semana-7 pull request #16
Opened 2023-06-04 03:03 UTC by fjquants

Realizando consulta a la pagina de https://dog.ceo/dog-api/ se realiza un proyecto con Nextjs en el que se muestra aleatoriamente la imagen de 10 razas de perros.

2023-06-09 16:38 UTC, pablo-alex commented on nextjs/fjquant-2458/components/card.js
> +        <img src={img} alt="dog" width={200} height={200}/>
Usa la etiqueta <Image> que te provee NextJS, en los otros componentes veo que si la usaste

2023-06-09 16:39 UTC, pablo-alex commented on nextjs/fjquant-2458/pages/index.js
> +// import { useEffect, useState } from 'react';
Limpia todo el codigo comentado que no tiene proposito

2023-06-09 16:48 UTC, pablo-alex commented on nextjs/fjquant-2458/pages/index.js
> +              })}
Aqui podrias simplificar el codigo usando solo un ciclo map no veo muy necesario tener dos, luego puedes acomodar bien las cards usando css y flex, ten cuidado que con dos contenedores exactamente iguales esta arrojando un warning en consola.

2023-06-09 16:48 UTC, pablo-alex requested changes
Hola @fjquants, ejecutando el proyecto veo que todo esta funcionando correctamente, te dejare algunos pequeños comentarios que puedes corregir

2023-06-09 17:36 UTC, fjquants commented on nextjs/fjquant-2458/pages/index.js
> +// import { useEffect, useState } from 'react';
Listo

2023-06-09 17:37 UTC, fjquants commented on nextjs/fjquant-2458/components/card.js
> +        <img src={img} alt="dog" width={200} height={200}/>
Aplicado la etiqueta Image

2023-06-09 17:38 UTC, fjquants commented on nextjs/fjquant-2458/pages/index.js
> +              })}
Utilicé dos veces el map para lograr tener las dos filas con diferentes razas de perros. Con un solo map de 10 razas no lograba colocarlo en dos filas.

2023-06-10 00:37 UTC, pablo-alex commented on nextjs/fjquant-2458/pages/index.js
> +              })}
podrias agregar a tus estilos en css lo siguiente, asi puedes controlar cuantos items por fila quieres mostrar:
`.entrada {
  flex-grow: 1;
  width: 20%;
}`
asi puedes ya podrias simplificar tu codigo
```suggestion
            <div className={styles.container}>
              {dogs.slice(0, 10).map((dog, index) => {
                return <Card key={index} title={dog.title} img={dog.img} />
              })}
```

2023-06-10 00:40 UTC, pablo-alex approved these changes

2023-06-10 02:03 UTC, fjquants commented on nextjs/fjquant-2458/components/card.js
> +        <img src={img} alt="dog" width={200} height={200}/>
Volví a dejar la etiqueta img, pues al colocar image tomaba src como prop, no como la ruta a la imagen

2023-06-10 02:03 UTC, fjquants commented on nextjs/fjquant-2458/pages/index.js
> +              })}
Excelente ayuda, ya lo ajusté. Gracias

2023-06-10 21:03 UTC, LizethCs approved these changes

2023-06-11 02:18 UTC, merged