Creando app random dogs
undefined-academy/semana-7 pull request #5
Opened 2023-05-25 02:58 UTC by Alexis033

Web usando Next.js que genera una lista de 10 cartas con razas de perro random con su respectiva imagen cada vez que se carga la página.

2023-05-25 15:16 UTC, adrian-gg requested changes

2023-05-25 15:16 UTC, adrian-gg commented on nextjs/maikcol-2796/pages/index.jsx
> +        const res = await fetch("https://dog.ceo/api/breeds/image/random/10")
Este enlace devuelve 10 perros de razas aleatorias. Lo que significa que la raza se puede repetir y que al final acabes imprimiendo dos perros de la misma raza. Si bien el enunciado se puede entender de varias formas, dando tu solución como correcta, aprovecharía la practica para complicar las cosas y ver como lo resolverías. 
Además, ya que estás en NextJs, consumiría la API desde el lado del servidor y no desde el lado del cliente como en React.

PD: Me gusta que hayas usado regex para obtener el nombre de la raza.
PDD: Las subrazas, has de cambiar el orden: "bulldog-french" --> "french bulldog"

2023-05-26 02:28 UTC, Alexis033 commented on nextjs/maikcol-2796/pages/index.jsx
> +        const res = await fetch("https://dog.ceo/api/breeds/image/random/10")
Hola, gracias por tus comentarios, tienes toda la razón, ya arreglé el orden de los nombres, evité que se repitan razas y use Route API.

2023-05-26 04:11 UTC, adrian-gg approved these changes
¡Perfesto!

2023-05-26 23:38 UTC, Pancratzia commented
Hola! Muy buen trabajo. Me gustó también que agregases la sugerencia que te ha dado Adrián, era algo que no había pensado. Sigue así!

2023-05-26 23:38 UTC, Pancratzia approved these changes

2023-05-27 16:54 UTC, merged