my firts commit with dogs y nextjs tailwind css
undefined-academy/semana-7 pull request #6
Opened 2023-05-25 16:11 UTC by marisolSv22

Proyecto en nextjs npx-create-next-app@latest (nombre-proyecto) con fetch de api de perritos y mapeo de 12 perritos aleatorios, estilos css con tailwind, estructura del PR

next
 ┗ marisolsalazarv-6177
 ┃ ┣ public
 ┃ ┃ ┣ next.svg
 ┃ ┃ ┗ vercel.svg
 ┃ ┣ src
 ┃ ┃ ┗ app
 ┃ ┃ ┃ ┣ favicon.ico
 ┃ ┃ ┃ ┣ globals.css
 ┃ ┃ ┃ ┣ layout.js
 ┃ ┃ ┃ ┣ page.js
 ┃ ┃ ┃ ┗ page.module.css
 ┃ ┣ .eslintrc.json
 ┃ ┣ .gitignore
 ┃ ┣ README.md
 ┃ ┣ jsconfig.json
 ┃ ┣ next.config.js
 ┃ ┗ package.json

2023-05-25 17:45 UTC, equiman requested changes

2023-05-25 17:45 UTC, equiman commented on nextjs/marisolsalazarv-6177/pages/api/dogs.js
Al consumir el api de esta forma lo estarías haciendo al lado del cliente como en React. La idea de implementarlo en Next es que este consumo se haga al lado del servidor.

Para ello esta carpeta api debe estar ubicada en la raiz.

2023-05-25 17:53 UTC, equiman commented
Vas muy bien, solo el cambio que recomiendo hacer de mover el consumo del API. 
Lo poder repasar en este video https://www.twitch.tv/videos/1821889413 mas o menos al 1:20 

No está dentro de los requerimientos, pero también sería bueno implementar la parte responsive para que cuando se redimensione la pantalla no se deformen las imágenes.

2023-05-26 23:31 UTC, Pancratzia requested changes
Hola. He revisado tu PR y creo que he visto lo mismo que ha visto equiman en la parte del responsive. De resto podría decirse que lo veo bien

2023-05-31 03:39 UTC, equiman commented
mejoro el responsive pero aun sigues consumiendo el api como en react (desde el lado del cliente) y no como en next (desde el lado del servidor)

2023-05-31 21:30 UTC, equiman commented
No había visto los cambios del API no me había dado cuenta de que no había bajado los últimos cambios con el `git pull`. Ya quedo implementado de la forma correcta desde el servidor! 

Excelente trabajo 👌

2023-05-31 21:48 UTC, equiman approved these changes

2023-06-27 21:15 UTC, MauBedoya approved these changes
Cumple con todo, me parece que el PR ya esta listo para el merge 👍
Te agradecería si le puedes dar una mirada a mi PR [aquí](https://github.com/undefined-academy/semana-7/pull/19) por favor!

2023-07-05 15:17 UTC, merged